substitutions:
  device_name: emdd665-minimal
  friendly_name: "MDD665 Minimal"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  project:
    name: sq9mdd.mdd665
    version: "1.0.0"

esp8266:
  board: esp01_1m

logger:
  baud_rate: 0
  level: WARN

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  mdd665_backend:
    url: https://github.com/SQ9MDD/mdd665-esphome
    ref: main
    files:
      - backend/mdd665_core.yaml
    refresh: 0s

# API
binary_sensor:
  # DI1..DI6, mapowane na backendowe diX
  - platform: template
    id: DI1
    name: "DI1"
    lambda: |-
      return id(di1).state;

  - platform: template
    id: DI2 
    name: "DI2"
    lambda: |-
      return id(di2).state;

  - platform: template
    id: DI3
    name: "DI3"
    lambda: |-
      return id(di3).state;

  - platform: template
    id: DI4
    name: "DI4"
    lambda: |-
      return id(di4).state;

  - platform: template
    id: DI5
    name: "DI5"
    lambda: |-
      return id(di5).state;

  - platform: template
    id: DI6
    name: "DI6"
    lambda: |-
      return id(di6).state;

switch:
  # DO1..DO6, mapowane na backendowe doX
  - platform: template
    id: DO1
    name: "DO1"
    lambda: |-
      return id(do1).state;
    turn_on_action:
      - switch.turn_on: do1
    turn_off_action:
      - switch.turn_off: do1

  - platform: template
    id: DO2
    name: "DO2"
    lambda: |-
      return id(do2).state;
    turn_on_action:
      - switch.turn_on: do2
    turn_off_action:
      - switch.turn_off: do2

  - platform: template
    id: DO3
    name: "DO3"
    lambda: |-
      return id(do3).state;
    turn_on_action:
      - switch.turn_on: do3
    turn_off_action:
      - switch.turn_off: do3

  - platform: template
    id: DO4
    name: "DO4"
    lambda: |-
      return id(do4).state;
    turn_on_action:
      - switch.turn_on: do4
    turn_off_action:
      - switch.turn_off: do4

  - platform: template
    name: "DO5"
    lambda: |-
      return id(do5).state;
    turn_on_action:
      - switch.turn_on: do5
    turn_off_action:
      - switch.turn_off: do5

  - platform: template
    name: "DO6"
    lambda: |-
      return id(do6).state;
    turn_on_action:
      - switch.turn_on: do6
    turn_off_action:
      - switch.turn_off: do6

sensor:
  - platform: template
    name: "AI1"
    id: AI1
    accuracy_decimals: 0
    lambda: |-
      return id(ai1).state;

  - platform: template
    name: "AI2"
    id: AI2
    accuracy_decimals: 0
    lambda: |-
      return id(ai2).state;

  - platform: template
    name: "AI3"
    id: AI3
    accuracy_decimals: 0
    lambda: |-
      return id(ai3).state;

  - platform: template
    name: "AI4"
    id: AI4
    accuracy_decimals: 0
    lambda: |-
      return id(ai4).state;

  - platform: template
    name: "AI5"
    id: AI5
    accuracy_decimals: 0
    lambda: |-
      return id(ai5).state;
