substitutions:
  device_name: mdd665
  friendly_name: "MDD665"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  project:
    name: sq9mdd.mdd665
    version: "1.0.0"

esp8266:
  board: esp01_1m

logger:
  baud_rate: 0
  level: WARN

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  mdd665_backend:
    url: https://raw.githubusercontent.com/SQ9MDD/mdd665-esphome/main/backend/mdd665_core.yaml

# PUBLICZNE API dla użytkownika

binary_sensor:
  # DI1..DI6, mapowane na backendowe diX
  - platform: template
    name: "MDD665 DI1"
    lambda: |-
      return id(di1).state;
    on_press:
      - switch.toggle: do1

  - platform: template
    name: "MDD665 DI2"
    lambda: |-
      return id(di2).state;
    on_press:
      - switch.toggle: do2

  - platform: template
    name: "MDD665 DI3"
    lambda: |-
      return id(di3).state;
    on_press:
      - switch.toggle: do3

  - platform: template
    name: "MDD665 DI4"
    lambda: |-
      return id(di4).state;
    on_press:
      - switch.toggle: do4

  - platform: template
    name: "MDD665 DI5"
    lambda: |-
      return id(di5).state;
    on_press:
      - switch.toggle: do5

  - platform: template
    name: "MDD665 DI6"
    lambda: |-
      return id(di6).state;
    on_press:
      - switch.toggle: do6

switch:
  # DO1..DO6, owijają backendowe doX
  - platform: template
    name: "MDD665 DO1"
    lambda: |-
      return id(do1).state;
    turn_on_action:
      - switch.turn_on: do1
    turn_off_action:
      - switch.turn_off: do1

  - platform: template
    name: "MDD665 DO2"
    lambda: |-
      return id(do2).state;
    turn_on_action:
      - switch.turn_on: do2
    turn_off_action:
      - switch.turn_off: do2

  - platform: template
    name: "MDD665 DO3"
    lambda: |-
      return id(do3).state;
    turn_on_action:
      - switch.turn_on: do3
    turn_off_action:
      - switch.turn_off: do3

  - platform: template
    name: "MDD665 DO4"
    lambda: |-
      return id(do4).state;
    turn_on_action:
      - switch.turn_on: do4
    turn_off_action:
      - switch.turn_off: do4

  - platform: template
    name: "MDD665 DO5"
    lambda: |-
      return id(do5).state;
    turn_on_action:
      - switch.turn_on: do5
    turn_off_action:
      - switch.turn_off: do5

  - platform: template
    name: "MDD665 DO6"
    lambda: |-
      return id(do6).state;
    turn_on_action:
      - switch.turn_on: do6
    turn_off_action:
      - switch.turn_off: do6

sensor:
  # AI1..AI4 jako temperatury z NTC 10k B3950 na dzielniku 10k
  - platform: template
    name: "AI1 Temperatura"
    id: ai1_temp
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    accuracy_decimals: 1
    lambda: |-
      float adc = id(ai1).state;
      if (isnan(adc) || adc <= 0 || adc >= 1023) {
        return NAN;
      }
      const float Rref = 10000.0f;
      const float R0   = 10000.0f;
      const float T0   = 298.15f;
      const float Beta = 3950.0f;
      float Rntc = Rref * (adc / (1023.0f - adc));
      float invT = 1.0f / T0 + (1.0f / Beta) * logf(Rntc / R0);
      float tempK = 1.0f / invT;
      return tempK - 273.15f;

  - platform: template
    name: "AI2 Temperatura"
    id: ai2_temp
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    accuracy_decimals: 1
    lambda: |-
      float adc = id(ai2).state;
      if (isnan(adc) || adc <= 0 || adc >= 1023) {
        return NAN;
      }
      const float Rref = 10000.0f;
      const float R0   = 10000.0f;
      const float T0   = 298.15f;
      const float Beta = 3950.0f;
      float Rntc = Rref * (adc / (1023.0f - adc));
      float invT = 1.0f / T0 + (1.0f / Beta) * logf(Rntc / R0);
      float tempK = 1.0f / invT;
      return tempK - 273.15f;

  - platform: template
    name: "AI3 Temperatura"
    id: ai3_temp
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    accuracy_decimals: 1
    lambda: |-
      float adc = id(ai3).state;
      if (isnan(adc) || adc <= 0 || adc >= 1023) {
        return NAN;
      }
      const float Rref = 10000.0f;
      const float R0   = 10000.0f;
      const float T0   = 298.15f;
      const float Beta = 3950.0f;
      float Rntc = Rref * (adc / (1023.0f - adc));
      float invT = 1.0f / T0 + (1.0f / Beta) * logf(Rntc / R0);
      float tempK = 1.0f / invT;
      return tempK - 273.15f;

  - platform: template
    name: "AI4 Temperatura"
    id: ai4_temp
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    accuracy_decimals: 1
    lambda: |-
      float adc = id(ai4).state;
      if (isnan(adc) || adc <= 0 || adc >= 1023) {
        return NAN;
      }
      const float Rref = 10000.0f;
      const float R0   = 10000.0f;
      const float T0   = 298.15f;
      const float Beta = 3950.0f;
      float Rntc = Rref * (adc / (1023.0f - adc));
      float invT = 1.0f / T0 + (1.0f / Beta) * logf(Rntc / R0);
      float tempK = 1.0f / invT;
      return tempK - 273.15f;

  - platform: template
    name: "AI5 Lux"
    id: ai5_lux
    unit_of_measurement: "lx"
    icon: "mdi:brightness-6"
    accuracy_decimals: 0
    lambda: |-
      float adc = id(ai5).state;
      if (isnan(adc)) return NAN;
      float x = (1023.0f - adc) / 1023.0f;
      if (x < 0.0f) x = 0.0f;
      if (x > 1.0f) x = 1.0f;
      const float gamma = 1.6f;
      float lux = 2000.0f * powf(x, gamma);
      return lux;
